// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/geraldkohn/elian/data/model"
)

func newPatient(db *gorm.DB) patient {
	_patient := patient{}

	_patient.patientDo.UseDB(db)
	_patient.patientDo.UseModel(&model.Patient{})

	tableName := _patient.patientDo.TableName()
	_patient.ALL = field.NewField(tableName, "*")
	_patient.Uid = field.NewString(tableName, "uid")
	_patient.Name = field.NewString(tableName, "name")
	_patient.Password = field.NewString(tableName, "password")
	_patient.IdCardNumber = field.NewString(tableName, "id_card_number")
	_patient.RegisterTime = field.NewString(tableName, "register_time")
	_patient.LastLoginTime = field.NewString(tableName, "last_login_time")
	_patient.Token = field.NewString(tableName, "token")

	_patient.fillFieldMap()

	return _patient
}

type patient struct {
	patientDo patientDo

	ALL           field.Field
	Uid           field.String
	Name          field.String
	Password      field.String
	IdCardNumber  field.String
	RegisterTime  field.String
	LastLoginTime field.String
	Token         field.String

	fieldMap map[string]field.Expr
}

func (p patient) Table(newTableName string) *patient {
	p.patientDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p patient) As(alias string) *patient {
	p.patientDo.DO = *(p.patientDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *patient) updateTableName(table string) *patient {
	p.ALL = field.NewField(table, "*")
	p.Uid = field.NewString(table, "uid")
	p.Name = field.NewString(table, "name")
	p.Password = field.NewString(table, "password")
	p.IdCardNumber = field.NewString(table, "id_card_number")
	p.RegisterTime = field.NewString(table, "register_time")
	p.LastLoginTime = field.NewString(table, "last_login_time")
	p.Token = field.NewString(table, "token")

	p.fillFieldMap()

	return p
}

func (p *patient) WithContext(ctx context.Context) *patientDo { return p.patientDo.WithContext(ctx) }

func (p patient) TableName() string { return p.patientDo.TableName() }

func (p patient) Alias() string { return p.patientDo.Alias() }

func (p *patient) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *patient) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["uid"] = p.Uid
	p.fieldMap["name"] = p.Name
	p.fieldMap["password"] = p.Password
	p.fieldMap["id_card_number"] = p.IdCardNumber
	p.fieldMap["register_time"] = p.RegisterTime
	p.fieldMap["last_login_time"] = p.LastLoginTime
	p.fieldMap["token"] = p.Token
}

func (p patient) clone(db *gorm.DB) patient {
	p.patientDo.ReplaceDB(db)
	return p
}

type patientDo struct{ gen.DO }

func (p patientDo) Debug() *patientDo {
	return p.withDO(p.DO.Debug())
}

func (p patientDo) WithContext(ctx context.Context) *patientDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p patientDo) Clauses(conds ...clause.Expression) *patientDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p patientDo) Returning(value interface{}, columns ...string) *patientDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p patientDo) Not(conds ...gen.Condition) *patientDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p patientDo) Or(conds ...gen.Condition) *patientDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p patientDo) Select(conds ...field.Expr) *patientDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p patientDo) Where(conds ...gen.Condition) *patientDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p patientDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *patientDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p patientDo) Order(conds ...field.Expr) *patientDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p patientDo) Distinct(cols ...field.Expr) *patientDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p patientDo) Omit(cols ...field.Expr) *patientDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p patientDo) Join(table schema.Tabler, on ...field.Expr) *patientDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p patientDo) LeftJoin(table schema.Tabler, on ...field.Expr) *patientDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p patientDo) RightJoin(table schema.Tabler, on ...field.Expr) *patientDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p patientDo) Group(cols ...field.Expr) *patientDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p patientDo) Having(conds ...gen.Condition) *patientDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p patientDo) Limit(limit int) *patientDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p patientDo) Offset(offset int) *patientDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p patientDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *patientDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p patientDo) Unscoped() *patientDo {
	return p.withDO(p.DO.Unscoped())
}

func (p patientDo) Create(values ...*model.Patient) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p patientDo) CreateInBatches(values []*model.Patient, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p patientDo) Save(values ...*model.Patient) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p patientDo) First() (*model.Patient, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Patient), nil
	}
}

func (p patientDo) Take() (*model.Patient, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Patient), nil
	}
}

func (p patientDo) Last() (*model.Patient, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Patient), nil
	}
}

func (p patientDo) Find() ([]*model.Patient, error) {
	result, err := p.DO.Find()
	return result.([]*model.Patient), err
}

func (p patientDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Patient, err error) {
	buf := make([]*model.Patient, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p patientDo) FindInBatches(result *[]*model.Patient, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p patientDo) Attrs(attrs ...field.AssignExpr) *patientDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p patientDo) Assign(attrs ...field.AssignExpr) *patientDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p patientDo) Joins(fields ...field.RelationField) *patientDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p patientDo) Preload(fields ...field.RelationField) *patientDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p patientDo) FirstOrInit() (*model.Patient, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Patient), nil
	}
}

func (p patientDo) FirstOrCreate() (*model.Patient, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Patient), nil
	}
}

func (p patientDo) FindByPage(offset int, limit int) (result []*model.Patient, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p patientDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p *patientDo) withDO(do gen.Dao) *patientDo {
	p.DO = *do.(*gen.DO)
	return p
}
